
#include <stdio.h>
#include <windows.h>
int main(void)
{
	HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    const long SLEEP_MILLISECONDS = 5;
	COORD pos;  /* структура, що м≥стить позиц≥ю курсора */
    pos.X = 0;  /* номер стовпц€ */
    pos.Y = 0;  /* номер р€дка */
	int i, j;
	int num = 0;
	int fl = 1;
    pos.X = 0;
	pos.Y = 0;
	int k =0;
	SetConsoleTextAttribute(hConsole, k);
	for (i = 0; i < 30; i++)
		for (j = 0; j < 80; j++)
		{
			pos.X = j;
			pos.Y = i;
			SetConsoleCursorPosition(hConsole, pos);
			putchar(' ');
		}
	i = 0;
	j = 23;
    while (!(i >= 80 && j <= 0)) {
		for (; (j >= 0) && (i >= 0); i--)
		{
		    //чомусь запускаЇтьс€ т≥льки так :(
			switch (j){
        case 0 : k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 1:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 2:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 3:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 4:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 15 :
            k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 16:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 17:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 18:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 19:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;

        case 5:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 6:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 7:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 8:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 9:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;

        case 20:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 21:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 22:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 23:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 24:
                k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 10 :k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 11:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 12:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 13:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 14:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;

			}
			SetConsoleTextAttribute(hConsole, k);
			pos.X = i;
			pos.Y = j;
			SetConsoleCursorPosition(hConsole, pos);
			printf(" ");
			Sleep(SLEEP_MILLISECONDS);
			j--;
		}
		i++;
		j++;
		if (i == 0)
		{
			j--;
		}
		else
			i++;
		for (; (i < 80) && (j < 24); i++)
		{
			switch (j){
        case 0 : k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 1:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 2:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 3:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 4:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 15 :
            k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 16:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 17:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 18:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 19:k = BACKGROUND_RED | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;

        case 5:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 6:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 7:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 8:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 9:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;

        case 20:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 21:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 22:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 23:k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 24:
                k = BACKGROUND_GREEN |BACKGROUND_RED| FOREGROUND_GREEN | FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 10 :k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 11:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 12:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 13:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
        case 14:k = BACKGROUND_BLUE | BACKGROUND_RED | FOREGROUND_BLUE| FOREGROUND_RED | BACKGROUND_INTENSITY | FOREGROUND_INTENSITY;
            break;
			}
			SetConsoleTextAttribute(hConsole, k);
			pos.X = i;
			pos.Y = j;
			SetConsoleCursorPosition(hConsole, pos);
			printf(" ");
			Sleep(SLEEP_MILLISECONDS);
			j++;
		}
		if (i == 80)
			j--;
		else
			i++;
		j--;
		i--;

    }
	k = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED;
	SetConsoleTextAttribute(hConsole, k);
	return EXIT_SUCCESS;
}
